%Function with the general adjusted settings for the plots made 
%Grid settings and smaller thicks settings can be specified

function p = setPlotStyle(grid, minorTicks)
    
    if(nargin<1)
        grid = {'on','on'};
    end
    
    if(nargin<2)
        minorTicks = {'on', 'on'};
    end
    
    set(gca, ...
      'Box'         , 'off'     , ... 
      ...
      'TickLength'  , [.02 0.2] , ...
      'TickDir'     , 'out'     , ...
      'XMinorTick'  , minorTicks{1}      , ...
      'YMinorTick'  , minorTicks{2}      , ...
      ...
      'XGrid'  , grid{1}     , ...
      'YGrid'  , grid{2}     , ...
      ...
      'XColor'      , [0.0, 0.0, 0.0], ...
      'YColor'      , [0.0, 0.0, 0.0], ...
      'LineWidth'   , 1);
end